config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html 
  root to: 'pages#home'
  resources :teams
    
  resources :team_members
  resources :users

  delete 'delete_team_member/:team_id/:user_id' => "teams#delete_team_member", as: "delete_team_member"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/speciality.rb
class Speciality < ApplicationRecord
    has_many :user_specialities
end

app/models/team.rb
class Team < ApplicationRecord
   has_many :team_members
   has_many :users, through: :team_members
end

app/models/team_member.rb
class TeamMember < ApplicationRecord
  belongs_to :user
  belongs_to :team
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_specialities, dependent: :destroy
    has_many :specialities, through: :user_specialities
    has_many :team_members, dependent: :destroy
end

app/models/user_speciality.rb
class UserSpeciality < ApplicationRecord
  belongs_to :user
  belongs_to :speciality
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end
end

app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
    def index
        @team = Team.find(params[:team_id])
        @users = User.all
    end

    def new
        @team_member = TeamMember.new
    end

    def create 
        @team = Team.find(params[:team_id])
        @user = User.find(params[:user_id])
        @team_member = TeamMember.new  
        @team_member.user = @user
        @team_member.team = @team
        @team_member.save

        redirect_to teams_path
    end 

    def update 
    end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
    
    def index
        @teams = Team.all
    end

    def show
        @team = Team.find(params[:id])
    end
    
    def new
        @team = Team.new
    end

    def create
        @team = Team.find(params[:id])
        @team = Team.create
    end
    
    def delete_team_member
        TeamMember.where(team_id: params[:team_id], user_id: params[:user_id]).destroy_all
        redirect_to teams_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all 
    end

    def show
        @user = User.find(params[:id])    
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/team_members_helper.rb
module TeamMembersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClinicalTeam</title>
    <%= csrf_meta_tags %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <div class="navbar navbar-expand-lg navbar-expand-md navbar-light  fixed-top">
          <div><i class="fas fa-h-square brand"></i></div>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
              <li class="nav-item active">
                <%= link_to "Home", "/", class: "nav-link"%>
              </li>
              <li>
                <%= link_to "Dashboard", teams_path, class: "nav-link"%>
              </li>
            </ul>
          </div>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    <%= yield %>
    <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
    <%= javascript_pack_tag "application" %>  
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-page">
</div>

app/views/team_members/create.html.erb
<h1>hello</h1>

app/views/team_members/index.html.erb
<div class="container mt-4">
    <br>
    <h2 style="text-align: center;">All Staff</h2>
    <div class="card p-4">
    <% @users.each do |user| %>
        <div class="card p-4 mb-2">
            <img src="<%=user.photo%>" alt="" style="width:50px; height:50px; border-radius:50%;">   
            <br>  
            <p><%= user.firstname %> <%= user.lastname %></p>
            <p><%= user.profession%></p>
            <%= link_to "Select", team_members_path(:team_id => @team.id, :user_id => user.id), :method => :post, class: "btn btn-secondary" %>
        </div>
    <%end%>
    <%= link_to "Back to teams", teams_path, class: "btn btn-dark" %>
</div>
</div>

app/views/users/index.html.erb
<div>
    <h1>Staff Members</h1>
    <%@users.each do |user| %>
    <img src="<%=user.photo%>" alt="" style="width:100px; height:100px; border-radius:50%;">
    <ul>    
        <li> <%=user.firstname%>  <%=user.lastname%>: title</li>        
    </ul>
    <%end%>
    <%= link_to "home", "/"%>
</div>

app/views/users/show.html.erb
<br>
<br>
<div class="container mt-4">
    <div class="card p-4">
        <h1><%=@user.firstname.capitalize%> <%=@user.lastname.capitalize%></h1>
        <img src="<%=@user.photo%>" alt="" style="width:100px; height:100px; border-radius:50%;">
            <p><%=@user.profession%></p>
            <% if @user.onleave == true %>
            <p>On Leave: <%= "yes" %></p> 
            <% else%>
            <p>On Leave: <%= "no" %></p> 
            <%end%>
            <p>Bio: <%=@user.bio%></p>
            <%@user.specialities.each do |spec|%>
                <p>Speciality: <%=spec.name%></p>
            <%end%>
            <%= link_to "Back", teams_path, class: "btn btn-dark mt-4"%>
    </div>
</div>